### ISSUE TITLE
Query release with format throws httparty error

### ISSUE THREAD

**Issue by travisdmathis** [dwo/musicbrainz-ruby#7]
BRAINZ.release(:query => "Junta AND artist:Phish AND format:Vinyl")
NoMethodError: undefined method `each_pair' for #<HTTParty::Response:0x007fdf499ee730>
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/httparty-0.10.2/lib/httparty/response.rb:56:in`method_missing'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/hashie-3.3.2/lib/hashie/mash.rb:178:in `deep_update'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/hashie-3.3.2/lib/hashie/mash.rb:89:in`initialize'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/bundler/gems/musicbrainz-ruby-2cf816cc7071/lib/musicbrainz/client.rb:94:in `new'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/bundler/gems/musicbrainz-ruby-2cf816cc7071/lib/musicbrainz/client.rb:94:in`request'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/bundler/gems/musicbrainz-ruby-2cf816cc7071/lib/musicbrainz/client.rb:46:in `release'
    from (irb):40
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/railties-4.1.6/lib/rails/commands/console.rb:90:in`start'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/railties-4.1.6/lib/rails/commands/console.rb:9:in `start'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:69:in`console'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/railties-4.1.6/lib/rails/commands.rb:17:in`<top (required)>'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in`block in require'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in`require'
... 1 levels...
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `load'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in`block in load'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in`load'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/spring-1.2.0/lib/spring/commands/rails.rb:6:in `call'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/spring-1.2.0/lib/spring/command_wrapper.rb:38:in`call'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/spring-1.2.0/lib/spring/application.rb:183:in `block in serve'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/spring-1.2.0/lib/spring/application.rb:156:in`fork'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/spring-1.2.0/lib/spring/application.rb:156:in `serve'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/spring-1.2.0/lib/spring/application.rb:131:in`block in run'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/spring-1.2.0/lib/spring/application.rb:125:in`run'
    from /Users/travis/.rvm/gems/ruby-2.1.3@rails416/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /Users/travis/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/travis/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in`<main>'2.1.3 :041 >

**Comment by dwo** [comment]
I wasn't able to reproduce this on ruby 2.1.3 with a minimal example (just musicbrainz-ruby in my Gemfile)

``` ruby
require 'musicbrainz'

brainz = MusicBrainz::Client.new

puts brainz.release(:query => "Junta AND artist:Phish AND format:Vinyl")
#=> <#Hashie::Mash created="2015-01-27T20:00:32.919Z" release_list=<#Hashie::Mash count="0" offset="0">>
```

It looks like perhaps it's something to do with Rails? Could you elaborate a bit on the context you're using this in?
